### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by Schildkroet** [GRRLIB/GRRLIB#4]
Hello,
i'm trying to build grrlib on linux, but i get  immediately this error:

```
pngu.c
pngu.c:1290:1: fatal error: opening dependency file /pngu.d: Permission denied
 }
 ^
compilation terminated.
/opt/devkitpro/devkitPPC/base_rules:17: recipe for target 'pngu.o' failed
make: *** [pngu.o] Error 1
```
This happens for every makefile. it seems the dependeny file is not generated correctly.

**Comment by Crayon2000** [comment]
Hello, I have just re-started CI on the last commit and it is still working well on Linux: https://travis-ci.org/GRRLIB/GRRLIB

Have you tried to do a `make clean` before calling `make`?

**Comment by Schildkroet** [comment]
Hello,
yes, i used `make clean all` as initial command (Also tried `make` and `make all`). I also changed to different dirs and repeated it, but i always get the the same error (Permission denied). I use Mint 19 (Ubuntu 18.04 LTS).

**Comment by Crayon2000** [comment]
Just to be sure, are you using version 4.3.2 or the latest committed code?

**Comment by Schildkroet** [comment]
The latest commited (cloned master)

**Comment by loopj** [comment]
Heads up that I'm seeing this exact issue when using the 4.4.0 release, or when building from master on macOS

**Comment by Crayon2000** [comment]
@loopj, how can you have problems with _pngu.c_ with GRRLIB 4.4.0? This file is not not included anymore in the repository?

In 4.4.0, since GRRLIB and libpngu are now installed into the porlibs folder, make sure you don't have any leftovers from previous installations. You will need to manually delete unneeded libraries in _devkitPro\libogc\lib\wii_ as well as include files in _devkitPro\libogc\include_. libpng must be removed from those folders with 4.4.0.

**Comment by ZLima12** [comment]
This issue is present in v4.4.0, but not the current master branch. I bisected between those two, and found commit 9fc4fe51e2e4f87a8e546aa3c64c639d0273d36c to be the fix. Could there be a version bump that includes this commit? Thanks.

**Comment by Crayon2000** [comment]
@ZLima12, GRRLIB v4.4.1 was released: https://github.com/GRRLIB/GRRLIB/releases/tag/v4.4.1
